[[constraint]]
  name = "github.com/influxdata/influxdb"
  version = "1.5.2"

[[constraint]]
  name = "go.opencensus.io"
  version = ">=0.12.0" 

[prune]
  go-tests = true
  non-go = true
  unused-packages = true
