[[constraint]]
  name = "github.com/influxdata/influxdb"
  version = "1.5.2"

[[constraint]]
  name = "go.opencensus.io"
  branch = "master"

[prune]
  go-tests = true
  non-go = true
  unused-packages = true
